create table Date_Dimension (
date_key int not null,
full_date datetime,
day_of_week tinyint,
day_num_in_month tinyint,
day_num_overall smallint,
day_name varchar(9),
day_abbrev char(3),
weekday_flag varchar(20),
week_num_in_year tinyint,
week_num_overall smallint,
week_begin_date datetime,
week_begin_date_key int,
month tinyint,
month_num_overall smallint,
month_name varchar(15),
month_abbrev char(3),
quarter tinyint,
year smallint,
yearmo int,
fiscal_month tinyint,
fiscal_quarter tinyint,
fiscal_year smallint,
last_day_in_month_flag varchar(20),
same_day_year_ago_date datetime,
primary key (date_key))

